### ISSUE TITLE
Твитерот да објавува колку долго бил отворен/ и можда затворен

### ISSUE THREAD

**Issue by gdamjan** [skopjehacklab/kika-info-bus#2]
Пошто twitter-status.py постојано ја следи состојбата на хаклабот може и да твита колку долго бил отворен. Дури и да даде споредба на температурите :) или така нешто

**Comment by gdamjan** [comment]
```
Traceback (most recent call last):
  File "/home/kikadevices/kika-info-bus/twitter-status/twitter-status.py", line 54, in <module>
    main()
  File "/home/kikadevices/kika-info-bus/twitter-status/twitter-status.py", line 48, in main
    time_opened  = calculate_opened(time_of_change - time_initial)
  File "/home/kikadevices/kika-info-bus/twitter-status/twitter-status.py", line 20, in calculate_opened
    minutes = (td.seconds()/60)%60
TypeError: 'int' object is not callable
[uwsgi-daemons] respawning "/home/kikadevices/kika-info-bus/twitter-status/twitter-status.py" (uid: 1001 gid: 20)
```
